In [2]:
import pandas as pd
import numpy as np

from scipy.stats import gmean
from scipy.optimize import root_scalar

from expon_mixture import ExponMixture

In [3]:
df = pd.read_csv("all_data.csv", index_col=0)

In [7]:
names = []
data = []
# Iterate over all rows
for index, row in df.iterrows():
    mean = np.mean(row[1:]) # For the computation of the speedup, the mean is needed
    cumsum = 0.0 # This is used for the conditional expectation
    current_min_exp = np.inf
    optimal_t = 0.0
    for i in range(1, 301): # The first column is the instance type. This is irrelevant here.
        t = row[i] 
        cumsum += float(t) # Updata the partial expectation
        ecdf = i/300.0 # We measured 300 runs
        geom_part = (1.0 - ecdf)/ecdf * t # This part describes the geometric part of the expectation with restarts
        cond_exp = cumsum / i # partial expectation -> conditional expectation
        if geom_part + cond_exp < current_min_exp: # Update the best restart time if necessary.
            current_min_exp = geom_part + cond_exp
            optimal_t = t
    names.append(index)
    data.append([row[0], mean, current_min_exp, mean/current_min_exp, optimal_t])

optimal_df = pd.DataFrame(data, index=names, columns=["type", "expectation no restarts" ,"expectation with best restarts", "speedup", "best restart time"])

In [8]:
optimal_df

,type,expectation no restarts,expectation with best restarts,speedup,best restart time
gen_n210_m903_k3SAT_seed2473397791.cnf,barthel,3.214107e+03,3.214107e+03,1.000000,1.293200e+04
gen_n210_m903_k3SAT_seed862748622.cnf,barthel,1.342518e+04,1.308250e+04,1.026194,1.180100e+04
gen_n210_m903_k3SAT_seed4006075830.cnf,barthel,1.295157e+03,1.293375e+03,1.001378,5.594000e+03
gen_n210_m903_k3SAT_seed1547818438.cnf,barthel,1.365623e+03,1.363372e+03,1.001652,4.191000e+03
gen_n210_m903_k3SAT_seed3919912883.cnf,barthel,1.511253e+03,1.500828e+03,1.006947,4.381000e+03
...,...,...,...,...,...
gen_n70_m385_k3SAT_seed2030441879.cnf,qhid,3.993567e+02,3.990936e+02,1.000659,1.710000e+03
gen_n70_m385_k3SAT_seed3717411169.cnf,qhid,2.097433e+02,2.097433e+02,1.000000,8.900000e+02
gen_n70_m385_k3SAT_seed684617509.cnf,qhid,2.370867e+02,2.305567e+02,1.028322,5.280000e+02
gen_n70_m385_k3SAT_seed1293934752.cnf,qhid,1.008646e+11,8.186059e+10,1.232151,4.239737e+10
gen_n70_m385_k3SAT_seed2538753387.cnf,qhid,1.949727e+07,1.857800e+04,1049.481649,1.240000e+02

# Calculate the average speedup over all instances

In [9]:
gmean(optimal_df['speedup'])

18.19553445091588

# Calculate the average speedup over the barthel instances

In [10]:
df1 = optimal_df[optimal_df['type'] == 'barthel']
gmean(df1['speedup'])

1.0984796379053687

# Calculate the average speedup over the komb instances

In [11]:
df1 = optimal_df[optimal_df['type'] == 'komb']
gmean(df1['speedup'])

156.9581117219696

# Calculate the average speedup over the qhid instances

In [12]:
df1 = optimal_df[optimal_df['type'] == 'qhid']
gmean(df1['speedup'])

34.93965989136677

# Calculate the average speedup over the qhid and komb instances

In [13]:
df1 = optimal_df[(optimal_df['type'] == 'qhid') | (optimal_df['type'] == 'komb')]
gmean(df1['speedup'])

74.05445996533072

# Calculate the average speedup on instances with two components

In [14]:
fits = pd.read_csv('../fits/expon_mix_2comp_fits_mod_name.txt', index_col=0)

In [15]:
df1 = optimal_df[fits['p1']<1.0]
gmean(df1['speedup'])

228.97264635150276

## Add the number of variables to the fit

In [16]:
features = pd.read_csv('../calculate_features/features_train_mod_name.csv')
features.set_index('instance', inplace=True)
fits['n'] = features[['nvarsOrig']]

In [17]:
fits.head()

                                         p1  p2       lambda1  lambda2      n
instance
gen_n210_m903_k3SAT_seed2473397791.cnf  1.0 NaN   3214.106667      NaN  210.0
gen_n210_m903_k3SAT_seed862748622.cnf   1.0 NaN  13425.176667      NaN  210.0
gen_n210_m903_k3SAT_seed4006075830.cnf  1.0 NaN   1295.156667      NaN  210.0
gen_n210_m903_k3SAT_seed1547818438.cnf  1.0 NaN   1365.623333      NaN  210.0
gen_n210_m903_k3SAT_seed3919912883.cnf  1.0 NaN   1511.253333      NaN  210.0

## Setup functions for numerical optimization

In [18]:
def condition(t, rv, b):
    if t <= 0:
        return -np.inf
    F = rv.cdf(t)
    result = (F - 1.0)*t
    result += F*(1-F)/(rv.pdf(t))
    result -= rv.partial_exp(t)
    return result - b

In [19]:
def find_restart_time(p1, lambda1, lambda2, n, c=1.5):
    ps = [p1, 1.0-p1]
    scales = [lambda1, lambda2]
    rv = ExponMixture(ps, scales)
    b = c*n
    solution = root_scalar(condition, args=(rv, b), x0=10.0*b, x1=b, method='secant', xtol=1.0)
    return np.ceil(solution.root + b)

In [20]:
def evaluate_restart_time(data, t):
    mean = np.mean(data) # For the computation of the speedup, the mean is needed
    cumsum = 0.0 # This is used for the conditional expectation
    i = 0
    while data[i] <= t:
        cumsum += data[i]
        i += 1
    if i == 0:
        return 0
    ecdf = i/300.0 # We measured 300 runs
    geom_part = (1.0 - ecdf)/ecdf * t # This part describes the geometric part of the expectation with restarts
    cond_exp = cumsum/float(i) # partial expectation -> conditional expectation
    speedup = mean/(geom_part + cond_exp)
    return speedup

## Calculate speedups

In [21]:
mixed_fits = fits[fits['p1']<1.0]
underestimate = 0
speedups = []
for index, row in mixed_fits.iterrows():
    restart_time = find_restart_time(row[0], row[2], row[3], row[4], c=1.5)
    speedup = evaluate_restart_time(np.asarray(df.loc[index])[1:],  restart_time)
    if speedup == 0:
        underestimate += 1
#         print(index, "lamba1", row[2], "lambda2", row[3], "restart time:", restart_time)
    else:
        print(speedup)
        speedups.append(speedup)

1.0297045668398577
1.002513935390249
1.1278374866172416
1.0080260263871315
1.0550916283813656
1.6240404654365284
1.0362653738363266
1.0170228369960141
4.079519536707226
1.0606755259057308
1.0406679110189865
1.049926997029503
0.8865885610633896
1.030593615177877
1.0793516449802116
107900.79292023435
9382.815243725503
1855847.2119447782
8.071205669328503
16.92435188949622
5289.386835150405
245.78003383143852
9.414259079976077
148.03102840415906
55933.505160439556
46245.8475305699
13.615590216334116
6.45254851517665
11299.055871820661
12.73735212925223
12.256130910229713
63512.927006238875
6.850333991365335
1.7890328657100358
173.94327216746223
379.0299943901607
107.99765368177644
327.412648520895
67.75177254225619
81.59516780205298
1705.4925838536305
12.877389872852262
1110.0546750681647
110.58047715392301
6249.48651547729
78.1799300563144
25.45336185931454
188.82925010489376
34949.53244293309
96.11912721442204
1.9810373934837182
3.954793197740398
1046.4821621232607
17.118582964806194
1600.4897183541061
1084.3621028056275
14.227073060934654
11.87523818713893
8.768250295360446
252.6511800553363
1267.4116087526825
27.26291968789407
40.652140242507436
1196.3563375799074
201.22593711467326
51.67553594411674
3528.6115335977156
6620.915953056235
211.82647019853394
7.742734215338281
881.3778290405412
4.27360082993308
37.98413611902502
17.134158995060634
3.6763242819602597
248.09157569854366
170.0551934990074
8.165566716634679
2754.6703757704436
128.8817677420505
405.53499263037446
32.43873587113219
2.4122605739019285
620.1968218182466
44815.78034950395
123.34368652137115
420.2655348382592
6510.379501330928
11.89048281990985
3935.0425632939405
2963.0738583978755
2813.7313690752967
131.76070035379172
144.38088863098338
43.95741329626945
1545.7240615850437
10.341073559555944
825.373705273878
214.20243612802926
934.4153161283779
3.124183428399881
1548.4515327654676
1.0432240498386518
1745.2790009031385
50.922482036640496
763.8260411267606
66.68714613416692
1.0126000852322579
1.0520880512216424
394.280143923092
2005.6500227072754
1210.9798249399807
114.51328507078507
1.0227377022486044
719.0099968834113
193.68268087563388
12.1334266749637
140.9934372649881
49.69803791270286
139.82284831705505
50.73586372105403
28.008073579184448
7.041500962226996
4885.706683249799
462.06955153422496
99.74185431702071
7226767.743784085
21707.276683932694
21124.31350838452
587.2494572866187
2837.3236600614664
3312.2842395772664
1.1102312099346663
101560.5726382861
123904.85964563688
1577.9025154259334
109.72823807316158
88.66375559150092
723.1768321481283
126544.23691132113
56.91850707371557
20.65459508818311
108.2899933386873
32.17609205935221
2933.1527167604154
1965.5430259269956
1826.6858141563164
591419.0718610932
5077.044210620854
60915.121201870505
1.006000841224729
10946.99094320471
618.156370227112

## Calculate average speedup

In [22]:
gmean(speedups)

157.35845337386866

In [56]:
print(underestimate)

4

# Average speedup on all instances

In [29]:
underestimate = 0
speedups = []
for index, row in fits.iterrows():
    if row[0] < 1.0:
        restart_time = find_restart_time(row[0], row[2], row[3], row[4], c=1.5)
        speedup = evaluate_restart_time(np.asarray(df.loc[index])[1:],  restart_time)
        if speedup == 0:
            underestimate += 1
        else:
            speedups.append(speedup)
    else:
        speedups.append(1.0) # In this case restarts are not performed, therefore no speedup or slowdown can be observed

p1            1.000000
p2                 NaN
lambda1    3214.106667
lambda2            NaN
n           210.000000
Name: gen_n210_m903_k3SAT_seed2473397791.cnf, dtype: float64
p1             1.000000
p2                  NaN
lambda1    13425.176667
lambda2             NaN
n            210.000000
Name: gen_n210_m903_k3SAT_seed862748622.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    1295.156667
lambda2            NaN
n           210.000000
Name: gen_n210_m903_k3SAT_seed4006075830.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    1365.623333
lambda2            NaN
n           210.000000
Name: gen_n210_m903_k3SAT_seed1547818438.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    1511.253333
lambda2            NaN
n           210.000000
Name: gen_n210_m903_k3SAT_seed3919912883.cnf, dtype: float64
p1         9.966667e-01
p2         3.333333e-03
lambda1    3.348084e+05
lambda2    3.207062e+06
n          2.100000e+02
Name: gen_n210_m903_k3SAT_seed2090369458.cnf, dtype: float64
p1             0.940000
p2             0.060000
lambda1     5999.400709
lambda2    30819.000000
n            210.000000
Name: gen_n210_m903_k3SAT_seed3877340932.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    8344.266667
lambda2            NaN
n           210.000000
Name: gen_n210_m903_k3SAT_seed418978019.cnf, dtype: float64
p1              1.00
p2               NaN
lambda1    218604.11
lambda2          NaN
n             210.00
Name: gen_n210_m903_k3SAT_seed832034019.cnf, dtype: float64
p1              1.000000
p2                   NaN
lambda1    245565.936667
lambda2              NaN
n             210.000000
Name: gen_n210_m903_k3SAT_seed1250623881.cnf, dtype: float64
p1             1.000000
p2                  NaN
lambda1    70427.606667
lambda2             NaN
n            210.000000
Name: gen_n210_m903_k3SAT_seed3420558613.cnf, dtype: float64
p1            1.00
p2             NaN
lambda1    6307.69
lambda2        NaN
n           210.00
Name: gen_n210_m903_k3SAT_seed3576518490.cnf, dtype: float64
p1            1.00
p2             NaN
lambda1    2707.76
lambda2        NaN
n           210.00
Name: gen_n210_m903_k3SAT_seed4086115941.cnf, dtype: float64
p1             1.00
p2              NaN
lambda1    19714.15
lambda2         NaN
n            210.00
Name: gen_n210_m903_k3SAT_seed2726955691.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    2576.463333
lambda2            NaN
n           210.000000
Name: gen_n210_m903_k3SAT_seed2210409897.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    1625.206667
lambda2            NaN
n           210.000000
Name: gen_n210_m903_k3SAT_seed3906320868.cnf, dtype: float64
p1            1.0
p2            NaN
lambda1    2890.3
lambda2       NaN
n           210.0
Name: gen_n210_m903_k3SAT_seed196207409.cnf, dtype: float64
p1           1.0
p2           NaN
lambda1    949.4
lambda2      NaN
n          210.0
Name: gen_n210_m903_k3SAT_seed2527888016.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    7983.776667
lambda2            NaN
n           210.000000
Name: gen_n210_m903_k3SAT_seed2814938700.cnf, dtype: float64
p1            1.00
p2             NaN
lambda1    1236.55
lambda2        NaN
n           210.00
Name: gen_n210_m903_k3SAT_seed3555821415.cnf, dtype: float64
p1            1.0
p2            NaN
lambda1    3991.5
lambda2       NaN
n           220.0
Name: gen_n220_m946_k3SAT_seed2163334659.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    1335.186667
lambda2            NaN
n           220.000000
Name: gen_n220_m946_k3SAT_seed3832864776.cnf, dtype: float64
p1            1.00
p2             NaN
lambda1    1418.14
lambda2        NaN
n           220.00
Name: gen_n220_m946_k3SAT_seed2997502133.cnf, dtype: float64
p1           1.000000
p2                NaN
lambda1    903.756667
lambda2           NaN
n          220.000000
Name: gen_n220_m946_k3SAT_seed1307063375.cnf, dtype: float64
p1            1.00
p2             NaN
lambda1    2270.12
lambda2        NaN
n           220.00
Name: gen_n220_m946_k3SAT_seed2768414827.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    1065.633333
lambda2            NaN
n           220.000000
Name: gen_n220_m946_k3SAT_seed2530408929.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    3628.616667
lambda2            NaN
n           220.000000
Name: gen_n220_m946_k3SAT_seed3459617285.cnf, dtype: float64
p1             1.00
p2              NaN
lambda1    11714.39
lambda2         NaN
n            220.00
Name: gen_n220_m946_k3SAT_seed513612264.cnf, dtype: float64
p1             0.830000
p2             0.170000
lambda1     8352.779116
lambda2    40940.960784
n            220.000000
Name: gen_n220_m946_k3SAT_seed1552099922.cnf, dtype: float64
p1            1.00
p2             NaN
lambda1    2539.42
lambda2        NaN
n           220.00
Name: gen_n220_m946_k3SAT_seed1051819048.cnf, dtype: float64
p1             0.993333
p2             0.006667
lambda1     3490.687919
lambda2    28111.000000
n            220.000000
Name: gen_n220_m946_k3SAT_seed3935451372.cnf, dtype: float64
p1             0.950000
p2             0.050000
lambda1     6371.736842
lambda2    37963.000000
n            220.000000
Name: gen_n220_m946_k3SAT_seed2720769240.cnf, dtype: float64
p1            1.00
p2             NaN
lambda1    2405.37
lambda2        NaN
n           220.00
Name: gen_n220_m946_k3SAT_seed2584484727.cnf, dtype: float64
p1            1.00
p2             NaN
lambda1    1780.91
lambda2        NaN
n           220.00
Name: gen_n220_m946_k3SAT_seed2148158613.cnf, dtype: float64
p1             1.00
p2              NaN
lambda1    17394.38
lambda2         NaN
n            220.00
Name: gen_n220_m946_k3SAT_seed4166258070.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    3091.513333
lambda2            NaN
n           220.000000
Name: gen_n220_m946_k3SAT_seed4193498716.cnf, dtype: float64
p1             1.00
p2              NaN
lambda1    12676.54
lambda2         NaN
n            220.00
Name: gen_n220_m946_k3SAT_seed1534933776.cnf, dtype: float64
p1            1.00
p2             NaN
lambda1    3019.21
lambda2        NaN
n           220.00
Name: gen_n220_m946_k3SAT_seed1845498498.cnf, dtype: float64
p1             0.060000
p2             0.940000
lambda1      974.833333
lambda2    36740.024823
n            220.000000
Name: gen_n220_m946_k3SAT_seed122071483.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    4028.293333
lambda2            NaN
n           220.000000
Name: gen_n220_m946_k3SAT_seed385204719.cnf, dtype: float64
p1            1.00
p2             NaN
lambda1    2172.72
lambda2        NaN
n           200.00
Name: gen_n200_m860_k3SAT_seed846804536.cnf, dtype: float64
p1            1.00
p2             NaN
lambda1    1328.92
lambda2        NaN
n           200.00
Name: gen_n200_m860_k3SAT_seed3245143494.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    5788.283333
lambda2            NaN
n           200.000000
Name: gen_n200_m860_k3SAT_seed1075832061.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    1536.886667
lambda2            NaN
n           200.000000
Name: gen_n200_m860_k3SAT_seed3456510286.cnf, dtype: float64
p1            1.0
p2            NaN
lambda1    6252.4
lambda2       NaN
n           200.0
Name: gen_n200_m860_k3SAT_seed1912172752.cnf, dtype: float64
p1             1.00
p2              NaN
lambda1    13605.19
lambda2         NaN
n            200.00
Name: gen_n200_m860_k3SAT_seed378425480.cnf, dtype: float64
p1            1.00
p2             NaN
lambda1    1871.12
lambda2        NaN
n           200.00
Name: gen_n200_m860_k3SAT_seed3626164986.cnf, dtype: float64
p1           1.00
p2            NaN
lambda1    974.04
lambda2       NaN
n          200.00
Name: gen_n200_m860_k3SAT_seed2620132035.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    1885.763333
lambda2            NaN
n           200.000000
Name: gen_n200_m860_k3SAT_seed3009686298.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    1984.736667
lambda2            NaN
n           200.000000
Name: gen_n200_m860_k3SAT_seed3450427736.cnf, dtype: float64
p1            1.00
p2             NaN
lambda1    1377.54
lambda2        NaN
n           200.00
Name: gen_n200_m860_k3SAT_seed1441313772.cnf, dtype: float64
p1           1.00
p2            NaN
lambda1    880.02
lambda2       NaN
n          200.00
Name: gen_n200_m860_k3SAT_seed3437188108.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    2815.066667
lambda2            NaN
n           200.000000
Name: gen_n200_m860_k3SAT_seed2945015644.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    3892.456667
lambda2            NaN
n           200.000000
Name: gen_n200_m860_k3SAT_seed400010023.cnf, dtype: float64
p1             1.000000
p2                  NaN
lambda1    10092.993333
lambda2             NaN
n            200.000000
Name: gen_n200_m860_k3SAT_seed1555381953.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    3126.836667
lambda2            NaN
n           200.000000
Name: gen_n200_m860_k3SAT_seed1824069727.cnf, dtype: float64
p1             1.000000
p2                  NaN
lambda1    18648.713333
lambda2             NaN
n            200.000000
Name: gen_n200_m860_k3SAT_seed4253032545.cnf, dtype: float64
p1             1.000000
p2                  NaN
lambda1    18835.276667
lambda2             NaN
n            200.000000
Name: gen_n200_m860_k3SAT_seed3004849140.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    2266.236667
lambda2            NaN
n           200.000000
Name: gen_n200_m860_k3SAT_seed1760699802.cnf, dtype: float64
p1             1.000000
p2                  NaN
lambda1    83587.906667
lambda2             NaN
n            200.000000
Name: gen_n200_m860_k3SAT_seed402783643.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    3716.333333
lambda2            NaN
n           190.000000
Name: gen_n190_m817_k3SAT_seed2377759021.cnf, dtype: float64
p1              0.953333
p2              0.046667
lambda1     85269.727273
lambda2    422515.285714
n             190.000000
Name: gen_n190_m817_k3SAT_seed2312003320.cnf, dtype: float64
p1             1.000000
p2                  NaN
lambda1    13941.063333
lambda2             NaN
n            190.000000
Name: gen_n190_m817_k3SAT_seed2847134115.cnf, dtype: float64
p1             0.990000
p2             0.010000
lambda1     2475.888889
lambda2    17405.666667
n            190.000000
Name: gen_n190_m817_k3SAT_seed2929389930.cnf, dtype: float64
p1             1.000000
p2                  NaN
lambda1    28423.906667
lambda2             NaN
n            190.000000
Name: gen_n190_m817_k3SAT_seed3747390255.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    2609.943333
lambda2            NaN
n           190.000000
Name: gen_n190_m817_k3SAT_seed3004431487.cnf, dtype: float64
p1            1.00
p2             NaN
lambda1    2684.18
lambda2        NaN
n           190.00
Name: gen_n190_m817_k3SAT_seed3457981464.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    1701.466667
lambda2            NaN
n           190.000000
Name: gen_n190_m817_k3SAT_seed3134573763.cnf, dtype: float64
p1             1.000000
p2                  NaN
lambda1    80100.306667
lambda2             NaN
n            190.000000
Name: gen_n190_m817_k3SAT_seed1171229349.cnf, dtype: float64
p1             1.000000
p2                  NaN
lambda1    19802.513333
lambda2             NaN
n            190.000000
Name: gen_n190_m817_k3SAT_seed1778144097.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    1653.923333
lambda2            NaN
n           190.000000
Name: gen_n190_m817_k3SAT_seed2316062977.cnf, dtype: float64
p1             1.000000
p2                  NaN
lambda1    14725.753333
lambda2             NaN
n            190.000000
Name: gen_n190_m817_k3SAT_seed850862736.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    4065.033333
lambda2            NaN
n           190.000000
Name: gen_n190_m817_k3SAT_seed2419862218.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    3984.576667
lambda2            NaN
n           190.000000
Name: gen_n190_m817_k3SAT_seed404629771.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    2193.323333
lambda2            NaN
n           190.000000
Name: gen_n190_m817_k3SAT_seed3910879954.cnf, dtype: float64
p1         2.333333e-02
p2         9.766667e-01
lambda1    3.064286e+03
lambda2    1.028937e+06
n          1.900000e+02
Name: gen_n190_m817_k3SAT_seed3130549867.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    2905.736667
lambda2            NaN
n           190.000000
Name: gen_n190_m817_k3SAT_seed828863743.cnf, dtype: float64
p1            1.00
p2             NaN
lambda1    1418.02
lambda2        NaN
n           190.00
Name: gen_n190_m817_k3SAT_seed3444200792.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    7829.926667
lambda2            NaN
n           190.000000
Name: gen_n190_m817_k3SAT_seed1140404237.cnf, dtype: float64
p1            1.0
p2            NaN
lambda1    1825.6
lambda2       NaN
n           190.0
Name: gen_n190_m817_k3SAT_seed2099557271.cnf, dtype: float64
p1             0.936667
p2             0.063333
lambda1     6180.921708
lambda2    32418.000000
n            180.000000
Name: gen_n180_m774_k3SAT_seed2464538601.cnf, dtype: float64
p1            1.00
p2             NaN
lambda1    1955.65
lambda2        NaN
n           180.00
Name: gen_n180_m774_k3SAT_seed2019726627.cnf, dtype: float64
p1             0.976667
p2             0.023333
lambda1     4988.334471
lambda2    31723.571429
n            180.000000
Name: gen_n180_m774_k3SAT_seed2083207871.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    2993.453333
lambda2            NaN
n           180.000000
Name: gen_n180_m774_k3SAT_seed94015970.cnf, dtype: float64
p1            1.00
p2             NaN
lambda1    2176.56
lambda2        NaN
n           180.00
Name: gen_n180_m774_k3SAT_seed158152504.cnf, dtype: float64
p1             0.963333
p2             0.036667
lambda1     1924.349481
lambda2    10844.636364
n            180.000000
Name: gen_n180_m774_k3SAT_seed3263018221.cnf, dtype: float64
p1           1.000000
p2                NaN
lambda1    671.816667
lambda2           NaN
n          180.000000
Name: gen_n180_m774_k3SAT_seed3307725434.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    2690.263333
lambda2            NaN
n           180.000000
Name: gen_n180_m774_k3SAT_seed346043754.cnf, dtype: float64
p1             0.166667
p2             0.833333
lambda1     1854.740000
lambda2    29288.944000
n            180.000000
Name: gen_n180_m774_k3SAT_seed1371750993.cnf, dtype: float64
p1              1.00
p2               NaN
lambda1    127399.44
lambda2          NaN
n             180.00
Name: gen_n180_m774_k3SAT_seed1940105.cnf, dtype: float64
p1             0.986667
p2             0.013333
lambda1     7080.523649
lambda2    45756.500000
n            180.000000
Name: gen_n180_m774_k3SAT_seed3530265751.cnf, dtype: float64
p1              0.960000
p2              0.040000
lambda1     43816.201389
lambda2    239047.750000
n             180.000000
Name: gen_n180_m774_k3SAT_seed1123655738.cnf, dtype: float64
p1             1.00
p2              NaN
lambda1    19569.05
lambda2         NaN
n            180.00
Name: gen_n180_m774_k3SAT_seed2518931408.cnf, dtype: float64
p1            1.00
p2             NaN
lambda1    2992.55
lambda2        NaN
n           180.00
Name: gen_n180_m774_k3SAT_seed625252808.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    1301.623333
lambda2            NaN
n           180.000000
Name: gen_n180_m774_k3SAT_seed2846784053.cnf, dtype: float64
p1            1.00
p2             NaN
lambda1    2010.71
lambda2        NaN
n           180.00
Name: gen_n180_m774_k3SAT_seed1602711602.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    1579.586667
lambda2            NaN
n           180.000000
Name: gen_n180_m774_k3SAT_seed3407369727.cnf, dtype: float64
p1             1.0
p2             NaN
lambda1    54430.5
lambda2        NaN
n            180.0
Name: gen_n180_m774_k3SAT_seed4146867239.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    1526.866667
lambda2            NaN
n           180.000000
Name: gen_n180_m774_k3SAT_seed3273696372.cnf, dtype: float64
p1            1.00
p2             NaN
lambda1    2940.55
lambda2        NaN
n           180.00
Name: gen_n180_m774_k3SAT_seed3156097730.cnf, dtype: float64
p1         3.333333e-03
p2         9.966667e-01
lambda1    2.590000e+02
lambda2    1.174607e+10
n          1.200000e+02
Name: gen_n120_m625_k3SAT_seed4002250474.cnf, dtype: float64
p1         3.333333e-03
p2         9.966667e-01
lambda1    8.470000e+02
lambda2    1.573925e+08
n          1.200000e+02
Name: gen_n120_m625_k3SAT_seed3741058123.cnf, dtype: float64
p1         3.333333e-03
p2         9.966667e-01
lambda1    1.110000e+02
lambda2    1.014389e+09
n          1.200000e+02
Name: gen_n120_m625_k3SAT_seed2998485883.cnf, dtype: float64
p1         1.000000e-02
p2         9.900000e-01
lambda1    2.586667e+02
lambda2    6.766656e+10
n          1.200000e+02
Name: gen_n120_m625_k3SAT_seed3898757036.cnf, dtype: float64
p1             0.106667
p2             0.893333
lambda1      635.187500
lambda2    78814.716418
n            120.000000
Name: gen_n120_m625_k3SAT_seed154293799.cnf, dtype: float64
p1              0.060000
p2              0.940000
lambda1      1476.277778
lambda2    597758.500000
n             120.000000
Name: gen_n120_m625_k3SAT_seed1193448330.cnf, dtype: float64
p1         3.333333e-03
p2         9.966667e-01
lambda1    2.020000e+02
lambda2    5.739126e+08
n          1.200000e+02
Name: gen_n120_m625_k3SAT_seed1461364855.cnf, dtype: float64
p1         5.666667e-02
p2         9.433333e-01
lambda1    5.943529e+02
lambda2    3.863422e+06
n          1.200000e+02
Name: gen_n120_m625_k3SAT_seed1563430074.cnf, dtype: float64
p1             1.000000
p2                  NaN
lambda1    12156.386667
lambda2             NaN
n            120.000000
Name: gen_n120_m625_k3SAT_seed924765564.cnf, dtype: float64
p1             0.216667
p2             0.783333
lambda1      973.600000
lambda2    84370.540426
n            120.000000
Name: gen_n120_m625_k3SAT_seed1632151664.cnf, dtype: float64

p1         3.000000e-02
p2         9.700000e-01
lambda1    6.172222e+02
lambda2    5.508872e+06
n          1.200000e+02
Name: gen_n120_m625_k3SAT_seed1819395239.cnf, dtype: float64
p1         3.333333e-03
p2         9.966667e-01
lambda1    4.160000e+02
lambda2    8.681853e+09
n          1.200000e+02
Name: gen_n120_m625_k3SAT_seed1815115026.cnf, dtype: float64
p1         3.333333e-03
p2         9.966667e-01
lambda1    5.460000e+02
lambda2    7.961122e+09
n          1.200000e+02
Name: gen_n120_m625_k3SAT_seed667779377.cnf, dtype: float64
p1         2.333333e-02
p2         9.766667e-01
lambda1    1.339643e+04
lambda2    5.171641e+06
n          1.200000e+02
Name: gen_n120_m625_k3SAT_seed117874758.cnf, dtype: float64
p1              0.026667
p2              0.973333
lambda1      1091.875000
lambda2    524798.726027
n             120.000000
Name: gen_n120_m625_k3SAT_seed3279182319.cnf, dtype: float64
p1         6.666667e-03
p2         9.933333e-01
lambda1    2.690000e+02
lambda2    1.232685e+09
n          1.200000e+02
Name: gen_n120_m625_k3SAT_seed1367797299.cnf, dtype: float64
p1         2.333333e-02
p2         9.766667e-01
lambda1    1.073429e+03
lambda2    1.004678e+06
n          1.200000e+02
Name: gen_n120_m625_k3SAT_seed1996703905.cnf, dtype: float64
p1              0.070000
p2              0.930000
lambda1      1690.238095
lambda2    375798.623656
n             120.000000
Name: gen_n120_m625_k3SAT_seed3460967358.cnf, dtype: float64
p1         2.333333e-02
p2         9.766667e-01
lambda1    4.862857e+02
lambda2    2.127765e+09
n          1.200000e+02
Name: gen_n120_m625_k3SAT_seed685731525.cnf, dtype: float64
p1         1.000000e+00
p2                  NaN
lambda1    2.498616e+10
lambda2             NaN
n          1.200000e+02
Name: gen_n120_m625_k3SAT_seed4111198820.cnf, dtype: float64
p1             0.126667
p2             0.873333
lambda1      870.710526
lambda2    86120.095420
n             90.000000
Name: gen_n90_m468_k3SAT_seed3667190761.cnf, dtype: float64
p1              0.003333
p2              0.996667
lambda1       151.000000
lambda2    190265.832776
n              90.000000
Name: gen_n90_m468_k3SAT_seed3181143732.cnf, dtype: float64
p1         2.333333e-02
p2         9.766667e-01
lambda1    1.884286e+02
lambda2    2.872909e+06
n          9.000000e+01
Name: gen_n90_m468_k3SAT_seed3160967033.cnf, dtype: float64
p1                1.00
p2                 NaN
lambda1    49977045.07
lambda2            NaN
n                90.00
Name: gen_n90_m468_k3SAT_seed2876470160.cnf, dtype: float64
p1         1.333333e-02
p2         9.866667e-01
lambda1    5.170000e+02
lambda2    1.803260e+07
n          9.000000e+01
Name: gen_n90_m468_k3SAT_seed1323436025.cnf, dtype: float64
p1           1.000000
p2                NaN
lambda1    397.356667
lambda2           NaN
n           90.000000
Name: gen_n90_m468_k3SAT_seed3474465536.cnf, dtype: float64
p1         6.666667e-03
p2         9.933333e-01
lambda1    4.925000e+02
lambda2    1.507698e+07
n          9.000000e+01
Name: gen_n90_m468_k3SAT_seed127978095.cnf, dtype: float64
p1         1.333333e-02
p2         9.866667e-01
lambda1    2.197500e+02
lambda2    1.132593e+07
n          9.000000e+01
Name: gen_n90_m468_k3SAT_seed911472862.cnf, dtype: float64
p1         7.000000e-02
p2         9.300000e-01
lambda1    1.018762e+03
lambda2    1.052693e+06
n          9.000000e+01
Name: gen_n90_m468_k3SAT_seed2606193618.cnf, dtype: float64
p1             1.000000
p2                  NaN
lambda1    41930.896667
lambda2             NaN
n             90.000000
Name: gen_n90_m468_k3SAT_seed153478261.cnf, dtype: float64
p1         1.666667e-02
p2         9.833333e-01
lambda1    2.502000e+02
lambda2    1.788108e+06
n          9.000000e+01
Name: gen_n90_m468_k3SAT_seed2536146026.cnf, dtype: float64
p1         1.666667e-02
p2         9.833333e-01
lambda1    2.426000e+02
lambda2    4.590477e+07
n          9.000000e+01
Name: gen_n90_m468_k3SAT_seed402418011.cnf, dtype: float64
p1              0.046667
p2              0.953333
lambda1       325.285714
lambda2    148425.671329
n              90.000000
Name: gen_n90_m468_k3SAT_seed136505588.cnf, dtype: float64
p1         3.333333e-03
p2         9.966667e-01
lambda1    1.470000e+02
lambda2    9.041117e+07
n          9.000000e+01
Name: gen_n90_m468_k3SAT_seed373399427.cnf, dtype: float64
p1         5.000000e-02
p2         9.500000e-01
lambda1    3.478000e+02
lambda2    1.174589e+06
n          9.000000e+01
Name: gen_n90_m468_k3SAT_seed2602510383.cnf, dtype: float64
p1            1.0
p2            NaN
lambda1    4027.1
lambda2       NaN
n            90.0
Name: gen_n90_m468_k3SAT_seed1812140442.cnf, dtype: float64
p1         1.333333e-02
p2         9.866667e-01
lambda1    2.875000e+02
lambda2    2.376325e+08
n          9.000000e+01
Name: gen_n90_m468_k3SAT_seed2342331445.cnf, dtype: float64
p1              0.066667
p2              0.933333
lambda1       441.000000
lambda2    798935.475000
n              90.000000
Name: gen_n90_m468_k3SAT_seed2906402158.cnf, dtype: float64
p1              0.030000
p2              0.970000
lambda1       328.444444
lambda2    523301.340206
n              90.000000
Name: gen_n90_m468_k3SAT_seed3831882065.cnf, dtype: float64
p1         5.000000e-02
p2         9.500000e-01
lambda1    2.391333e+02
lambda2    1.737018e+06
n          9.000000e+01
Name: gen_n90_m468_k3SAT_seed1080542041.cnf, dtype: float64
p1         2.333333e-02
p2         9.766667e-01
lambda1    3.024286e+02
lambda2    7.752057e+08
n          1.100000e+02
Name: gen_n110_m573_k3SAT_seed2156362608.cnf, dtype: float64
p1         1.333333e-02
p2         9.866667e-01
lambda1    3.717500e+02
lambda2    4.577051e+06
n          1.100000e+02
Name: gen_n110_m573_k3SAT_seed1194819985.cnf, dtype: float64
p1         3.333333e-03
p2         9.966667e-01
lambda1    6.030000e+02
lambda2    1.099288e+08
n          1.100000e+02
Name: gen_n110_m573_k3SAT_seed27911968.cnf, dtype: float64
p1         9.766667e-01
p2         2.333333e-02
lambda1    5.248641e+09
lambda2    3.670305e+10
n          1.100000e+02
Name: gen_n110_m573_k3SAT_seed1929338155.cnf, dtype: float64
p1              0.050000
p2              0.950000
lambda1      1111.200000
lambda2    141959.031579
n             110.000000
Name: gen_n110_m573_k3SAT_seed3259052812.cnf, dtype: float64
p1         2.000000e-02
p2         9.800000e-01
lambda1    8.553333e+02
lambda2    6.924257e+07
n          1.100000e+02
Name: gen_n110_m573_k3SAT_seed1910634195.cnf, dtype: float64
p1              0.046667
p2              0.953333
lambda1       462.357143
lambda2    348159.468531
n             110.000000
Name: gen_n110_m573_k3SAT_seed2340505847.cnf, dtype: float64
p1         1.333333e-02
p2         9.866667e-01
lambda1    4.157500e+02
lambda2    7.917287e+07
n          1.100000e+02
Name: gen_n110_m573_k3SAT_seed1152085199.cnf, dtype: float64
p1         2.000000e-02
p2         9.800000e-01
lambda1    2.241667e+02
lambda2    2.189614e+07
n          1.100000e+02
Name: gen_n110_m573_k3SAT_seed1801823909.cnf, dtype: float64
p1              0.023333
p2              0.976667
lambda1       633.857143
lambda2    644467.624573
n             110.000000
Name: gen_n110_m573_k3SAT_seed2337222594.cnf, dtype: float64
p1         6.666667e-03
p2         9.933333e-01
lambda1    1.609000e+03
lambda2    3.159201e+06
n          1.100000e+02
Name: gen_n110_m573_k3SAT_seed1597986796.cnf, dtype: float64
p1              0.026667
p2              0.973333
lambda1       727.000000
lambda2    564229.000000
n             110.000000
Name: gen_n110_m573_k3SAT_seed3870658024.cnf, dtype: float64
p1         1.000000e+00
p2                  NaN
lambda1    2.226272e+07
lambda2             NaN
n          1.100000e+02
Name: gen_n110_m573_k3SAT_seed3476477324.cnf, dtype: float64
p1         4.000000e-02
p2         9.600000e-01
lambda1    5.968333e+02
lambda2    5.576362e+06
n          1.100000e+02
Name: gen_n110_m573_k3SAT_seed2530876845.cnf, dtype: float64
p1         1.666667e-02
p2         9.833333e-01
lambda1    3.930000e+02
lambda2    4.634666e+07
n          1.100000e+02
Name: gen_n110_m573_k3SAT_seed4272717496.cnf, dtype: float64
p1              0.036667
p2              0.963333
lambda1       275.363636
lambda2    398965.211073
n             110.000000
Name: gen_n110_m573_k3SAT_seed2186428039.cnf, dtype: float64
p1              0.203333
p2              0.796667
lambda1      2904.983607
lambda2    891428.460251
n             110.000000
Name: gen_n110_m573_k3SAT_seed4018851091.cnf, dtype: float64
p1         3.333333e-03
p2         9.966667e-01
lambda1    4.170000e+02
lambda2    1.760060e+08
n          1.100000e+02
Name: gen_n110_m573_k3SAT_seed3733616460.cnf, dtype: float64
p1         5.333333e-02
p2         9.466667e-01
lambda1    5.390000e+02
lambda2    3.447735e+06
n          1.100000e+02
Name: gen_n110_m573_k3SAT_seed4077622523.cnf, dtype: float64
p1              0.096667
p2              0.903333
lambda1       827.517241
lambda2    863774.446494
n             110.000000
Name: gen_n110_m573_k3SAT_seed946785249.cnf, dtype: float64
p1         6.666667e-03
p2         9.933333e-01
lambda1    1.500000e+02
lambda2    1.280921e+08
n          8.000000e+01
Name: gen_n80_m416_k3SAT_seed726208581.cnf, dtype: float64
p1         2.000000e-02
p2         9.800000e-01
lambda1    1.201667e+02
lambda2    8.059389e+07
n          8.000000e+01
Name: gen_n80_m416_k3SAT_seed4106135924.cnf, dtype: float64
p1         4.666667e-02
p2         9.533333e-01
lambda1    6.108571e+02
lambda2    3.465703e+06
n          8.000000e+01
Name: gen_n80_m416_k3SAT_seed478163328.cnf, dtype: float64
p1           1.0
p2           NaN
lambda1    172.5
lambda2      NaN
n           80.0
Name: gen_n80_m416_k3SAT_seed3184935164.cnf, dtype: float64
p1              0.020000
p2              0.980000
lambda1       304.000000
lambda2    220353.591837
n              80.000000
Name: gen_n80_m416_k3SAT_seed1181241944.cnf, dtype: float64
p1         3.666667e-02
p2         9.633333e-01
lambda1    1.750000e+02
lambda2    8.209959e+06
n          8.000000e+01
Name: gen_n80_m416_k3SAT_seed1051802513.cnf, dtype: float64
p1             0.103333
p2             0.896667
lambda1      278.741935
lambda2    23913.401487
n             80.000000
Name: gen_n80_m416_k3SAT_seed958682847.cnf, dtype: float64
p1              0.04
p2              0.96
lambda1       323.75
lambda2    624944.25
n              80.00
Name: gen_n80_m416_k3SAT_seed242886304.cnf, dtype: float64
p1              0.026667
p2              0.973333
lambda1       817.875000
lambda2    715140.958904
n              80.000000
Name: gen_n80_m416_k3SAT_seed599310826.cnf, dtype: float64
p1             0.253333
p2             0.746667
lambda1      385.526316
lambda2    11735.736607
n             80.000000
Name: gen_n80_m416_k3SAT_seed364522462.cnf, dtype: float64
p1         2.333333e-02
p2         9.766667e-01
lambda1    1.620000e+02
lambda2    3.607612e+06
n          8.000000e+01
Name: gen_n80_m416_k3SAT_seed393353684.cnf, dtype: float64
p1         1.000000e-02
p2         9.900000e-01
lambda1    1.526667e+02
lambda2    4.787768e+06
n          8.000000e+01
Name: gen_n80_m416_k3SAT_seed3163119786.cnf, dtype: float64
p1              0.073333
p2              0.926667
lambda1       570.409091
lambda2    157198.561151
n              80.000000
Name: gen_n80_m416_k3SAT_seed3707026330.cnf, dtype: float64
p1         4.666667e-02
p2         9.533333e-01
lambda1    2.077143e+02
lambda2    2.222926e+07
n          8.000000e+01
Name: gen_n80_m416_k3SAT_seed1550730040.cnf, dtype: float64
p1            1.000000
p2                 NaN
lambda1    3823.803333
lambda2            NaN
n            80.000000
Name: gen_n80_m416_k3SAT_seed440213416.cnf, dtype: float64
p1             1.000000
p2                  NaN
lambda1    15177.976667
lambda2             NaN
n             80.000000
Name: gen_n80_m416_k3SAT_seed2746317214.cnf, dtype: float64
p1         4.666667e-02
p2         9.533333e-01
lambda1    3.450714e+02
lambda2    1.685015e+06
n          8.000000e+01
Name: gen_n80_m416_k3SAT_seed107420370.cnf, dtype: float64
p1         1.333333e-02
p2         9.866667e-01
lambda1    2.765000e+02
lambda2    1.412878e+07
n          8.000000e+01
Name: gen_n80_m416_k3SAT_seed3646664649.cnf, dtype: float64
p1              0.040000
p2              0.960000
lambda1       221.083333
lambda2    359392.458333
n              80.000000
Name: gen_n80_m416_k3SAT_seed4070888060.cnf, dtype: float64
p1              0.040000
p2              0.960000
lambda1      3206.250000
lambda2    405466.663194
n              80.000000
Name: gen_n80_m416_k3SAT_seed3588440357.cnf, dtype: float64
p1              1.00
p2               NaN
lambda1    105341.09
lambda2          NaN
n             100.00
Name: gen_n100_m520_k3SAT_seed3694720282.cnf, dtype: float64
p1         7.000000e-02
p2         9.300000e-01
lambda1    5.075714e+02
lambda2    7.683887e+06
n          1.000000e+02
Name: gen_n100_m520_k3SAT_seed2925930102.cnf, dtype: float64
p1         1.666667e-02
p2         9.833333e-01
lambda1    4.256000e+02
lambda2    1.583710e+09
n          1.000000e+02
Name: gen_n100_m520_k3SAT_seed939042956.cnf, dtype: float64
p1         6.666667e-03
p2         9.933333e-01
lambda1    2.410000e+02
lambda2    7.042012e+06
n          1.000000e+02
Name: gen_n100_m520_k3SAT_seed3105313243.cnf, dtype: float64
p1         2.333333e-02
p2         9.766667e-01
lambda1    2.098571e+02
lambda2    7.704265e+06
n          1.000000e+02
Name: gen_n100_m520_k3SAT_seed854001194.cnf, dtype: float64
p1         1.666667e-02
p2         9.833333e-01
lambda1    3.850000e+02
lambda2    2.959839e+08
n          1.000000e+02
Name: gen_n100_m520_k3SAT_seed2791232394.cnf, dtype: float64
p1             0.293333
p2             0.706667
lambda1      975.454545
lambda2    75866.622642
n            100.000000
Name: gen_n100_m520_k3SAT_seed2742213520.cnf, dtype: float64
p1         1.000000e-02
p2         9.900000e-01
lambda1    2.260000e+02
lambda2    1.197366e+08
n          1.000000e+02
Name: gen_n100_m520_k3SAT_seed999270937.cnf, dtype: float64
p1         3.333333e-03
p2         9.966667e-01
lambda1    2.430700e+04
lambda2    1.345307e+07
n          1.000000e+02
Name: gen_n100_m520_k3SAT_seed2170484434.cnf, dtype: float64
p1         1.666667e-02
p2         9.833333e-01
lambda1    1.880000e+02
lambda2    5.407961e+07
n          1.000000e+02
Name: gen_n100_m520_k3SAT_seed1690206282.cnf, dtype: float64
p1         2.666667e-02
p2         9.733333e-01
lambda1    3.462500e+02
lambda2    6.216996e+07
n          1.000000e+02
Name: gen_n100_m520_k3SAT_seed2585650757.cnf, dtype: float64
p1         1.000000e-02
p2         9.900000e-01
lambda1    7.356667e+02
lambda2    2.307276e+07
n          1.000000e+02
Name: gen_n100_m520_k3SAT_seed2410529191.cnf, dtype: float64

p1         3.000000e-02
p2         9.700000e-01
lambda1    5.240000e+02
lambda2    7.524113e+06
n          1.000000e+02
Name: gen_n100_m520_k3SAT_seed3012167821.cnf, dtype: float64
p1              0.070000
p2              0.930000
lambda1       646.619048
lambda2    717187.641577
n             100.000000
Name: gen_n100_m520_k3SAT_seed1849712020.cnf, dtype: float64
p1         2.333333e-02
p2         9.766667e-01
lambda1    4.265714e+02
lambda2    3.693752e+07
n          1.000000e+02
Name: gen_n100_m520_k3SAT_seed680249218.cnf, dtype: float64
p1              0.020000
p2              0.980000
lambda1       918.500000
lambda2    693227.129252
n             100.000000
Name: gen_n100_m520_k3SAT_seed113971124.cnf, dtype: float64
p1         1.000000e-02
p2         9.900000e-01
lambda1    2.620000e+02
lambda2    4.857366e+07
n          1.000000e+02
Name: gen_n100_m520_k3SAT_seed2496252241.cnf, dtype: float64
p1         1.333333e-02
p2         9.866667e-01
lambda1    6.155000e+02
lambda2    1.750171e+07
n          1.000000e+02
Name: gen_n100_m520_k3SAT_seed3075280818.cnf, dtype: float64
p1         3.666667e-02
p2         9.633333e-01
lambda1    2.769091e+02
lambda2    1.275395e+07
n          1.000000e+02
Name: gen_n100_m520_k3SAT_seed4293759542.cnf, dtype: float64
p1             0.023333
p2             0.976667
lambda1      214.000000
lambda2    28408.962457
n            100.000000
Name: gen_n100_m520_k3SAT_seed3451733972.cnf, dtype: float64
p1         2.666667e-02
p2         9.733333e-01
lambda1    3.712500e+01
lambda2    7.027092e+06
n          4.000000e+01
Name: gen_n40_m220_k3SAT_seed920842828.cnf, dtype: float64
p1           1.00
p2            NaN
lambda1    181.98
lambda2       NaN
n           40.00
Name: gen_n40_m220_k3SAT_seed3551386828.cnf, dtype: float64
p1           0.863333
p2           0.136667
lambda1    114.057915
lambda2    584.585366
n           40.000000
Name: gen_n40_m220_k3SAT_seed1117783044.cnf, dtype: float64
p1          1.000000
p2               NaN
lambda1    67.833333
lambda2          NaN
n          40.000000
Name: gen_n40_m220_k3SAT_seed741588491.cnf, dtype: float64
p1         2.000000e-02
p2         9.800000e-01
lambda1    2.533333e+01
lambda2    1.051679e+07
n          4.000000e+01
Name: gen_n40_m220_k3SAT_seed3437897286.cnf, dtype: float64
p1             0.093333
p2             0.906667
lambda1       81.892857
lambda2    98349.654412
n             40.000000
Name: gen_n40_m220_k3SAT_seed830799656.cnf, dtype: float64
p1         2.000000e-02
p2         9.800000e-01
lambda1    3.666667e+01
lambda2    4.611534e+06
n          4.000000e+01
Name: gen_n40_m220_k3SAT_seed1547240116.cnf, dtype: float64
p1          1.00
p2           NaN
lambda1    50.61
lambda2      NaN
n          40.00
Name: gen_n40_m220_k3SAT_seed4049979599.cnf, dtype: float64
p1              0.030000
p2              0.970000
lambda1        82.111111
lambda2    368383.786942
n              40.000000
Name: gen_n40_m220_k3SAT_seed3464545457.cnf, dtype: float64
p1           0.920000
p2           0.080000
lambda1    150.931159
lambda2    776.333333
n           40.000000
Name: gen_n40_m220_k3SAT_seed1167147743.cnf, dtype: float64
p1           0.730000
p2           0.270000
lambda1     88.292237
lambda2    459.938272
n           40.000000
Name: gen_n40_m220_k3SAT_seed110121578.cnf, dtype: float64
p1         2.333333e-02
p2         9.766667e-01
lambda1    4.714286e+01
lambda2    2.063655e+06
n          4.000000e+01
Name: gen_n40_m220_k3SAT_seed2751736756.cnf, dtype: float64
p1         5.333333e-02
p2         9.466667e-01
lambda1    5.431250e+01
lambda2    4.976128e+06
n          4.000000e+01
Name: gen_n40_m220_k3SAT_seed707889030.cnf, dtype: float64
p1         1.333333e-02
p2         9.866667e-01
lambda1    4.075000e+01
lambda2    1.094883e+07
n          4.000000e+01
Name: gen_n40_m220_k3SAT_seed456053775.cnf, dtype: float64
p1           1.000000
p2                NaN
lambda1    128.876667
lambda2           NaN
n           40.000000
Name: gen_n40_m220_k3SAT_seed3983477514.cnf, dtype: float64
p1              0.020000
p2              0.980000
lambda1        69.000000
lambda2    847396.901361
n              40.000000
Name: gen_n40_m220_k3SAT_seed3560184494.cnf, dtype: float64
p1           1.000000
p2                NaN
lambda1    182.616667
lambda2           NaN
n           40.000000
Name: gen_n40_m220_k3SAT_seed3348981652.cnf, dtype: float64
p1            0.986667
p2            0.013333
lambda1     216.290541
lambda2    1559.500000
n            40.000000
Name: gen_n40_m220_k3SAT_seed1124077025.cnf, dtype: float64
p1          1.000000
p2               NaN
lambda1    85.803333
lambda2          NaN
n          40.000000
Name: gen_n40_m220_k3SAT_seed2305023087.cnf, dtype: float64
p1         4.666667e-02
p2         9.533333e-01
lambda1    4.921429e+01
lambda2    1.901406e+06
n          4.000000e+01
Name: gen_n40_m220_k3SAT_seed1188342907.cnf, dtype: float64
p1          1.000000
p2               NaN
lambda1    29.743333
lambda2          NaN
n          30.000000
Name: gen_n30_m165_k3SAT_seed953174253.cnf, dtype: float64
p1              0.050000
p2              0.950000
lambda1        41.666667
lambda2    386722.414035
n              30.000000
Name: gen_n30_m165_k3SAT_seed1242859371.cnf, dtype: float64
p1          1.000000
p2               NaN
lambda1    30.486667
lambda2          NaN
n          30.000000
Name: gen_n30_m165_k3SAT_seed252746183.cnf, dtype: float64
p1          1.000000
p2               NaN
lambda1    94.643333
lambda2          NaN
n          30.000000
Name: gen_n30_m165_k3SAT_seed443094728.cnf, dtype: float64
p1          1.000000
p2               NaN
lambda1    43.306667
lambda2          NaN
n          30.000000
Name: gen_n30_m165_k3SAT_seed2056767044.cnf, dtype: float64
p1             0.073333
p2             0.926667
lambda1       31.454545
lambda2    15300.388489
n             30.000000
Name: gen_n30_m165_k3SAT_seed1013818840.cnf, dtype: float64
p1          1.000000
p2               NaN
lambda1    45.573333
lambda2          NaN
n          30.000000
Name: gen_n30_m165_k3SAT_seed3942586890.cnf, dtype: float64
p1          1.00
p2           NaN
lambda1    81.72
lambda2      NaN
n          30.00
Name: gen_n30_m165_k3SAT_seed3286348377.cnf, dtype: float64
p1              0.036667
p2              0.963333
lambda1        18.000000
lambda2    294874.737024
n              30.000000
Name: gen_n30_m165_k3SAT_seed3097603022.cnf, dtype: float64
p1          1.00
p2           NaN
lambda1    98.44
lambda2      NaN
n          30.00
Name: gen_n30_m165_k3SAT_seed1302657533.cnf, dtype: float64
p1             0.086667
p2             0.913333
lambda1       45.846154
lambda2    59834.208029
n             30.000000
Name: gen_n30_m165_k3SAT_seed285680178.cnf, dtype: float64
p1              0.083333
p2              0.916667
lambda1        39.440000
lambda2    172465.963636
n              30.000000
Name: gen_n30_m165_k3SAT_seed665600859.cnf, dtype: float64
p1          1.000000
p2               NaN
lambda1    29.026667
lambda2          NaN
n          30.000000
Name: gen_n30_m165_k3SAT_seed1701057194.cnf, dtype: float64
p1           1.000000
p2                NaN
lambda1    213.103333
lambda2           NaN
n           30.000000
Name: gen_n30_m165_k3SAT_seed85114132.cnf, dtype: float64
p1             0.083333
p2             0.916667
lambda1       40.240000
lambda2    60646.454545
n             30.000000
Name: gen_n30_m165_k3SAT_seed1724820279.cnf, dtype: float64
p1          1.000000
p2               NaN
lambda1    88.353333
lambda2          NaN
n          30.000000
Name: gen_n30_m165_k3SAT_seed4252124243.cnf, dtype: float64
p1             0.066667
p2             0.933333
lambda1       37.050000
lambda2    41840.467857
n             30.000000
Name: gen_n30_m165_k3SAT_seed2234840152.cnf, dtype: float64
p1          1.00
p2           NaN
lambda1    61.04
lambda2      NaN
n          30.00
Name: gen_n30_m165_k3SAT_seed2359662951.cnf, dtype: float64
p1             0.063333
p2             0.936667
lambda1       45.684211
lambda2    13171.313167
n             30.000000
Name: gen_n30_m165_k3SAT_seed3437916672.cnf, dtype: float64
p1          1.00
p2           NaN
lambda1    83.28
lambda2      NaN
n          30.00
Name: gen_n30_m165_k3SAT_seed386977620.cnf, dtype: float64
p1         1.333333e-02
p2         9.866667e-01
lambda1    7.350000e+01
lambda2    6.668742e+07
n          6.000000e+01
Name: gen_n60_m330_k3SAT_seed3080127367.cnf, dtype: float64
p1           1.000000
p2                NaN
lambda1    179.166667
lambda2           NaN
n           60.000000
Name: gen_n60_m330_k3SAT_seed65054740.cnf, dtype: float64
p1          1.000000
p2               NaN
lambda1    95.193333
lambda2          NaN
n          60.000000
Name: gen_n60_m330_k3SAT_seed2744776747.cnf, dtype: float64
p1          1.000000
p2               NaN
lambda1    77.153333
lambda2          NaN
n          60.000000
Name: gen_n60_m330_k3SAT_seed3592574582.cnf, dtype: float64
p1         3.000000e-02
p2         9.700000e-01
lambda1    7.900000e+01
lambda2    2.825450e+06
n          6.000000e+01
Name: gen_n60_m330_k3SAT_seed1674765457.cnf, dtype: float64
p1          1.000000
p2               NaN
lambda1    66.053333
lambda2          NaN
n          60.000000
Name: gen_n60_m330_k3SAT_seed2247046193.cnf, dtype: float64
p1         1.000000e+00
p2                  NaN
lambda1    1.462119e+09
lambda2             NaN
n          6.000000e+01
Name: gen_n60_m330_k3SAT_seed651213125.cnf, dtype: float64
p1           1.0
p2           NaN
lambda1    110.6
lambda2      NaN
n           60.0
Name: gen_n60_m330_k3SAT_seed1705680003.cnf, dtype: float64
p1           1.0
p2           NaN
lambda1    311.1
lambda2      NaN
n           60.0
Name: gen_n60_m330_k3SAT_seed2323465142.cnf, dtype: float64
p1           1.000000
p2                NaN
lambda1    313.173333
lambda2           NaN
n           60.000000
Name: gen_n60_m330_k3SAT_seed646892614.cnf, dtype: float64
p1         2.000000e-02
p2         9.800000e-01
lambda1    2.153333e+02
lambda2    1.596395e+06
n          6.000000e+01
Name: gen_n60_m330_k3SAT_seed3728226181.cnf, dtype: float64
p1         1.000000e-02
p2         9.900000e-01
lambda1    6.366667e+01
lambda2    1.305466e+11
n          6.000000e+01
Name: gen_n60_m330_k3SAT_seed2019766389.cnf, dtype: float64
p1           1.000000
p2                NaN
lambda1    135.053333
lambda2           NaN
n           60.000000
Name: gen_n60_m330_k3SAT_seed2726705792.cnf, dtype: float64
p1         3.333333e-03
p2         9.966667e-01
lambda1    4.300000e+01
lambda2    1.173129e+09
n          6.000000e+01
Name: gen_n60_m330_k3SAT_seed4276262007.cnf, dtype: float64
p1         3.333333e-03
p2         9.966667e-01
lambda1    6.900000e+01
lambda2    1.142175e+09
n          6.000000e+01
Name: gen_n60_m330_k3SAT_seed3183652506.cnf, dtype: float64
p1         2.333333e-02
p2         9.766667e-01
lambda1    1.184286e+02
lambda2    5.397381e+06
n          6.000000e+01
Name: gen_n60_m330_k3SAT_seed2045921457.cnf, dtype: float64
p1         1.666667e-02
p2         9.833333e-01
lambda1    8.020000e+01
lambda2    3.104474e+07
n          6.000000e+01
Name: gen_n60_m330_k3SAT_seed2360647896.cnf, dtype: float64
p1         3.333333e-03
p2         9.966667e-01
lambda1    2.100000e+01
lambda2    1.312362e+08
n          6.000000e+01
Name: gen_n60_m330_k3SAT_seed3976433077.cnf, dtype: float64
p1         9.866667e-01
p2         1.333333e-02
lambda1    4.516672e+08
lambda2    2.945188e+09
n          6.000000e+01
Name: gen_n60_m330_k3SAT_seed3698061794.cnf, dtype: float64
p1         6.666667e-03
p2         9.933333e-01
lambda1    1.035000e+02
lambda2    2.767952e+09
n          6.000000e+01
Name: gen_n60_m330_k3SAT_seed996097415.cnf, dtype: float64
p1         1.666667e-02
p2         9.833333e-01
lambda1    5.800000e+01
lambda2    1.122452e+09
n          5.000000e+01
Name: gen_n50_m275_k3SAT_seed3933953014.cnf, dtype: float64
p1          1.000000
p2               NaN
lambda1    48.806667
lambda2          NaN
n          50.000000

Name: gen_n50_m275_k3SAT_seed823534632.cnf, dtype: float64
p1          1.000000
p2               NaN
lambda1    57.973333
lambda2          NaN
n          50.000000
Name: gen_n50_m275_k3SAT_seed56556070.cnf, dtype: float64
p1         1.000000e-02
p2         9.900000e-01
lambda1    6.900000e+01
lambda2    2.393630e+07
n          5.000000e+01
Name: gen_n50_m275_k3SAT_seed2015337561.cnf, dtype: float64
p1         1.333333e-02
p2         9.866667e-01
lambda1    7.625000e+01
lambda2    1.259381e+06
n          5.000000e+01
Name: gen_n50_m275_k3SAT_seed1006443828.cnf, dtype: float64
p1              0.033333
p2              0.966667
lambda1       189.800000
lambda2    874855.765517
n              50.000000
Name: gen_n50_m275_k3SAT_seed1113916997.cnf, dtype: float64
p1           1.000000
p2                NaN
lambda1    140.176667
lambda2           NaN
n           50.000000
Name: gen_n50_m275_k3SAT_seed2601030206.cnf, dtype: float64
p1           1.000000
p2                NaN
lambda1    166.206667
lambda2           NaN
n           50.000000
Name: gen_n50_m275_k3SAT_seed1588945317.cnf, dtype: float64
p1         1.000000e-02
p2         9.900000e-01
lambda1    5.600000e+01
lambda2    1.088856e+07
n          5.000000e+01
Name: gen_n50_m275_k3SAT_seed281444314.cnf, dtype: float64
p1         2.000000e-02
p2         9.800000e-01
lambda1    6.050000e+01
lambda2    9.632212e+08
n          5.000000e+01
Name: gen_n50_m275_k3SAT_seed2337446731.cnf, dtype: float64
p1              0.066667
p2              0.933333
lambda1        92.100000
lambda2    163796.753571
n              50.000000
Name: gen_n50_m275_k3SAT_seed2494740734.cnf, dtype: float64
p1              0.036667
p2              0.963333
lambda1       123.181818
lambda2    136963.626298
n              50.000000
Name: gen_n50_m275_k3SAT_seed3596902314.cnf, dtype: float64
p1           1.000000
p2                NaN
lambda1    494.473333
lambda2           NaN
n           50.000000
Name: gen_n50_m275_k3SAT_seed2687448231.cnf, dtype: float64
p1         6.666667e-03
p2         9.933333e-01
lambda1    1.005000e+02
lambda2    2.918542e+06
n          5.000000e+01
Name: gen_n50_m275_k3SAT_seed2036044447.cnf, dtype: float64
p1           1.00
p2            NaN
lambda1    103.23
lambda2       NaN
n           50.00
Name: gen_n50_m275_k3SAT_seed3903345312.cnf, dtype: float64
p1              0.050000
p2              0.950000
lambda1       119.533333
lambda2    160157.263158
n              50.000000
Name: gen_n50_m275_k3SAT_seed1022050302.cnf, dtype: float64
p1         1.333333e-02
p2         9.866667e-01
lambda1    5.575000e+01
lambda2    3.316370e+07
n          5.000000e+01
Name: gen_n50_m275_k3SAT_seed560161642.cnf, dtype: float64
p1         1.333333e-02
p2         9.866667e-01
lambda1    8.175000e+01
lambda2    2.988887e+07
n          5.000000e+01
Name: gen_n50_m275_k3SAT_seed2593816830.cnf, dtype: float64
p1           1.000000
p2                NaN
lambda1    103.976667
lambda2           NaN
n           50.000000
Name: gen_n50_m275_k3SAT_seed2365602029.cnf, dtype: float64
p1          1.00
p2           NaN
lambda1    81.97
lambda2      NaN
n          50.00
Name: gen_n50_m275_k3SAT_seed2545373331.cnf, dtype: float64
p1         6.666667e-03
p2         9.933333e-01
lambda1    1.720000e+02
lambda2    1.166701e+08
n          7.000000e+01
Name: gen_n70_m385_k3SAT_seed3774472249.cnf, dtype: float64
p1         3.333333e-03
p2         9.966667e-01
lambda1    1.140000e+02
lambda2    3.750447e+10
n          7.000000e+01
Name: gen_n70_m385_k3SAT_seed2554429720.cnf, dtype: float64
p1         1.000000e-02
p2         9.900000e-01
lambda1    1.533333e+02
lambda2    1.617885e+08
n          7.000000e+01
Name: gen_n70_m385_k3SAT_seed1664766191.cnf, dtype: float64
p1           1.00
p2            NaN
lambda1    225.08
lambda2       NaN
n           70.00
Name: gen_n70_m385_k3SAT_seed4112418595.cnf, dtype: float64
p1         6.666667e-03
p2         9.933333e-01
lambda1    1.035000e+02
lambda2    1.934311e+09
n          7.000000e+01
Name: gen_n70_m385_k3SAT_seed3952042576.cnf, dtype: float64
p1         3.333333e-03
p2         9.966667e-01
lambda1    3.362350e+05
lambda2    9.181117e+08
n          7.000000e+01
Name: gen_n70_m385_k3SAT_seed183777491.cnf, dtype: float64
p1           1.000000
p2                NaN
lambda1    211.286667
lambda2           NaN
n           70.000000
Name: gen_n70_m385_k3SAT_seed3338197567.cnf, dtype: float64
p1           1.000000
p2                NaN
lambda1    219.203333
lambda2           NaN
n           70.000000
Name: gen_n70_m385_k3SAT_seed2675342406.cnf, dtype: float64
p1           1.00
p2            NaN
lambda1    177.92
lambda2       NaN
n           70.00
Name: gen_n70_m385_k3SAT_seed133194447.cnf, dtype: float64
p1            0.976667
p2            0.023333
lambda1     262.423208
lambda2    1536.142857
n            70.000000
Name: gen_n70_m385_k3SAT_seed3350403034.cnf, dtype: float64
p1         6.666667e-03
p2         9.933333e-01
lambda1    8.650000e+01
lambda2    3.474255e+08
n          7.000000e+01
Name: gen_n70_m385_k3SAT_seed3537208388.cnf, dtype: float64
p1                1.00
p2                 NaN
lambda1    57972188.13
lambda2            NaN
n                70.00
Name: gen_n70_m385_k3SAT_seed275012946.cnf, dtype: float64
p1           1.000000
p2                NaN
lambda1    101.423333
lambda2           NaN
n           70.000000
Name: gen_n70_m385_k3SAT_seed1157200205.cnf, dtype: float64
p1         1.000000e+00
p2                  NaN
lambda1    2.775735e+10
lambda2             NaN
n          7.000000e+01
Name: gen_n70_m385_k3SAT_seed3256574099.cnf, dtype: float64
p1         1.000000e-02
p2         9.900000e-01
lambda1    7.954321e+06
lambda2    1.269927e+10
n          7.000000e+01
Name: gen_n70_m385_k3SAT_seed3087325217.cnf, dtype: float64
p1           1.000000
p2                NaN
lambda1    399.356667
lambda2           NaN
n           70.000000
Name: gen_n70_m385_k3SAT_seed2030441879.cnf, dtype: float64
p1           1.000000
p2                NaN
lambda1    209.743333
lambda2           NaN
n           70.000000
Name: gen_n70_m385_k3SAT_seed3717411169.cnf, dtype: float64
p1           1.000000
p2                NaN
lambda1    237.086667
lambda2           NaN
n           70.000000
Name: gen_n70_m385_k3SAT_seed684617509.cnf, dtype: float64
p1         1.000000e+00
p2                  NaN
lambda1    1.008646e+11
lambda2             NaN
n          7.000000e+01
Name: gen_n70_m385_k3SAT_seed1293934752.cnf, dtype: float64
p1         6.666667e-03
p2         9.933333e-01
lambda1    1.020000e+02
lambda2    1.962812e+07
n          7.000000e+01
Name: gen_n70_m385_k3SAT_seed2538753387.cnf, dtype: float64

In [25]:
print(speedups)

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0297045668398577, 1.002513935390249, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.1278374866172416, 1.0, 1.0080260263871315, 1.0550916283813656, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.6240404654365284, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0362653738363266, 1.0, 1.0170228369960141, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 4.079519536707226, 1.0, 1.0, 1.0, 1.0, 1.0606755259057308, 1.0, 1.0406679110189865, 1.0, 1.0, 1.049926997029503, 1.0, 1.0, 0.8865885610633896, 1.0, 1.030593615177877, 1.0793516449802116, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 107900.79292023435, 9382.815243725503, 1855847.2119447782, 8.071205669328503, 16.92435188949622, 5289.386835150405, 245.78003383143852, 1.0, 9.414259079976077, 148.03102840415906, 55933.505160439556, 46245.8475305699, 13.615590216334116, 6.45254851517665, 11299.055871820661, 12.73735212925223, 12.256130910229713, 63512.927006238875, 1.0, 6.850333991365335, 1.7890328657100358, 173.94327216746223, 1.0, 379.0299943901607, 1.0, 107.99765368177644, 327.412648520895, 67.75177254225619, 1.0, 81.59516780205298, 1705.4925838536305, 12.877389872852262, 1110.0546750681647, 110.58047715392301, 1.0, 6249.48651547729, 78.1799300563144, 25.45336185931454, 188.82925010489376, 34949.53244293309, 96.11912721442204, 1.9810373934837182, 3.954793197740398, 1046.4821621232607, 17.118582964806194, 1600.4897183541061, 1084.3621028056275, 14.227073060934654, 11.87523818713893, 8.768250295360446, 1.0, 252.6511800553363, 1267.4116087526825, 27.26291968789407, 40.652140242507436, 1196.3563375799074, 201.22593711467326, 51.67553594411674, 3528.6115335977156, 6620.915953056235, 211.82647019853394, 1.0, 7.742734215338281, 881.3778290405412, 4.27360082993308, 37.98413611902502, 17.134158995060634, 3.6763242819602597, 248.09157569854366, 170.0551934990074, 8.165566716634679, 2754.6703757704436, 1.0, 1.0, 128.8817677420505, 405.53499263037446, 32.43873587113219, 2.4122605739019285, 1.0, 620.1968218182466, 44815.78034950395, 123.34368652137115, 420.2655348382592, 6510.379501330928, 11.89048281990985, 3935.0425632939405, 2963.0738583978755, 2813.7313690752967, 131.76070035379172, 144.38088863098338, 43.95741329626945, 1545.7240615850437, 10.341073559555944, 825.373705273878, 214.20243612802926, 934.4153161283779, 3.124183428399881, 1548.4515327654676, 1.0, 1.0432240498386518, 1.0, 1745.2790009031385, 50.922482036640496, 763.8260411267606, 1.0, 66.68714613416692, 1.0126000852322579, 1.0520880512216424, 394.280143923092, 2005.6500227072754, 1210.9798249399807, 1.0, 114.51328507078507, 1.0, 1.0227377022486044, 1.0, 719.0099968834113, 1.0, 193.68268087563388, 1.0, 1.0, 1.0, 12.1334266749637, 1.0, 1.0, 140.9934372649881, 1.0, 49.69803791270286, 139.82284831705505, 1.0, 1.0, 50.73586372105403, 1.0, 28.008073579184448, 1.0, 7.041500962226996, 1.0, 4885.706683249799, 1.0, 1.0, 1.0, 462.06955153422496, 1.0, 1.0, 1.0, 1.0, 1.0, 99.74185431702071, 7226767.743784085, 1.0, 21707.276683932694, 21124.31350838452, 587.2494572866187, 2837.3236600614664, 3312.2842395772664, 1.1102312099346663, 101560.5726382861, 123904.85964563688, 1.0, 1.0, 1577.9025154259334, 109.72823807316158, 88.66375559150092, 1.0, 1.0, 723.1768321481283, 126544.23691132113, 56.91850707371557, 20.65459508818311, 1.0, 108.2899933386873, 1.0, 32.17609205935221, 2933.1527167604154, 1965.5430259269956, 1.0, 1.0, 1826.6858141563164, 591419.0718610932, 5077.044210620854, 1.0, 60915.121201870505, 1.0, 1.0, 1.0, 1.006000841224729, 10946.99094320471, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 618.156370227112]

In [26]:
gmean(speedups)

13.784912277825212

In [27]:
underestimate

5